on:
  workflow_call:
    outputs:
      json:
        description: "JSON list with open PRs"
        value: ${{ jobs.list-open-prs.outputs.json }}

jobs:
  list-open-prs:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.remap.outputs.json }}
    steps:
      - name: List and remap open PRs
        id: remap
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          json=$(gh api "/repos/${{ github.repository }}/pulls?state=open&per_page=100" \
            | jq -c '{include: [.[] | {pr: .number, head_sha: .head.sha}]}')
          echo "json=$json" >> $GITHUB_OUTPUT
